#:schema https://www.schemastore.org/prek.json

[[repos]]
repo = "local"
hooks = [
  { id = "rustfmt", name = "rustfmt", entry = "cargo fmt --all -- --check", language = "system", files = "\\.rs$", pass_filenames = false },
  { id = "oxk-format", name = "oxk format", entry = "pnpm run format:oxk", language = "system", files = "\\.(ets|js|ts|json5)$", pass_filenames = false },
  { id = "oxk-lint", name = "oxk lint", entry = "pnpm run lint:oxk", language = "system", files = "\\.(ets|js|ts)$", pass_filenames = false },
]
