name: Format & Lint

on:
  pull_request:
    types: [opened, reopened, synchronize]

concurrency:
  group: pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  pull-requests: write

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Setup OpenHarmony SDK
        uses: openharmony-rs/setup-ohos-sdk@v0.1
        id: setup-ohos
        with:
          version: "5.0.0"

      - name: setup Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "stable"
          components: "clippy"
          target: "aarch64-unknown-linux-ohos,armv7-unknown-linux-ohos,x86_64-unknown-linux-ohos"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.22.0
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Check
        run: pnpm check
